global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'octabyte-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:3000']
        labels:
          environment: 'staging'
          service: 'octabyte-microservice'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
