name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: Build, Scan and Push
    runs-on: ubuntu-latest

    steps:

      # 1. Get the source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: app/package-lock.json

      # 3. Install application dependencies
      - name: Install dependencies
        working-directory: app
        run: npm ci

      # 4. Run application tests
      - name: Run tests
        working-directory: app
        run: npm test

      # 5. Build Docker image
      - name: Build Docker image
        working-directory: app
        run: |
          docker build -t octabyte-app:${{ github.sha }} .

      # 6. Scan Docker image for vulnerabilities
      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: octabyte-app:${{ github.sha }}
          format: table
          exit-code: "0"
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      # 7. Show GitHub repository information
      - name: Show GitHub OIDC information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Repository ID: ${{ github.repository_id }}"
          echo "Owner: ${{ github.repository_owner }}"
          echo "Owner ID: ${{ github.repository_owner_id }}"
          echo "Branch: ${{ github.ref_name }}"

      # 8. Configure AWS using GitHub OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          audience: sts.amazonaws.com

      # 9. Check AWS connection
      - name: Check AWS identity
        run: |
          aws sts get-caller-identity

      # 10. Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 11. Push Docker image to ECR
      - name: Push Docker image
        env:
          ECR_REPOSITORY: octabyte-staging-app
          IMAGE_TAG: ${{ github.sha }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker tag octabyte-app:${IMAGE_TAG} \
            ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

          docker push \
            ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
